### ISSUE TITLE
KeyError: 'state_dict'

### ISSUE THREAD

**Issue by titanlambda** [Rudrabha/Wav2Lip#142] opened 2020-11-12 04:14 UTC
While running inference.py this is the error:

Traceback (most recent call last):
  File "inference.py", line 279, in <module>
    main()
  File "inference.py", line 251, in main
    model = load_model(args.checkpoint_path)
  File "inference.py", line 171, in load_model
    s = checkpoint["state_dict"]
KeyError: 'state_dict'

<img width="951" alt="wav2Lip_error" src="https://user-images.githubusercontent.com/4718398/98894828-afb88a80-24cb-11eb-8c31-20c0f61934f1.png">

**Comment by titanlambda** [comment] 2020-11-12 04:20
Requirements.txt
librosa==0.7.0
numpy==1.17.1
opencv-contrib-python>=4.2.0.34
opencv-python==4.1.0.25
tensorflow==1.13.1
torch==1.1.0
torchvision==0.3.0
tqdm==4.45.0
numba==0.48

**Comment by prajwalkr** [comment] 2020-11-12 05:15
Please check if the checkpoint file is not corrupted.

**Comment by prajwalkr** [comment] 2020-11-14 09:09
Possible duplicate of https://github.com/Rudrabha/Wav2Lip/issues/141, please comment there if your issue is not resolved

**Closed by prajwalkr** 2020-11-14 09:09 UTC
